import = ["~/.config/alacritty/themes/themes/catppuccin.toml"]
live_config_reload = true

[cursor]
blink_timeout = 3

[cursor.style]
blinking = "Always"
shape = "Block"

[cursor.vi_mode_style]
blinking = "Always"
shape = "Block"

[env]
TERM = "tmux-256color"

[font]
size = 18

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleMaximized"
key = "F4"

[selection]
save_to_clipboard = true

[window]
decorations = "Buttonless"
dynamic_padding = true
dynamic_title = true
opacity = 0.8

[window.dimensions]
columns = 120
lines = 35

[window.padding]
# y = 28
